In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.2)

In [8]:
#Logistic Regression


lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Users\DELL PC\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9611111111111111

In [9]:
#SVM


svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.39166666666666666

In [10]:
#Random Forest


rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9611111111111111

In [ ]:
"""
findings
1. Logistic Regress : 96%
2. SVM : 46%
3. RF : 97%

In [11]:
#KFold cross validation
#Basic example


from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [9]:
#cross_val_score function

In [13]:
from sklearn.model_selection import cross_val_score

In [19]:
#Logistic regression model performance using cross_val_score


s1=cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=5)
s1

array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])

In [20]:
np.average(s1)

0.9221138966264315

In [21]:
#svm model performance using cross_val_score
s2=cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=5)
s2

array([0.41111111, 0.45      , 0.454039  , 0.44846797, 0.47910864])

In [22]:
np.average(s2)

0.448545341999381

In [23]:
#random forest performance using cross_val_score


s3=cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=5)
s3

array([0.93611111, 0.88888889, 0.95821727, 0.96100279, 0.91643454])

In [24]:
np.average(s3)

0.9321309192200558

In [14]:
# Parameter tunning using k fold cross validation

In [25]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8764804469273744

In [26]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9359993792675356

In [27]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9404345127250154

In [28]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9415859714463066